name: rabbitmq-support-tools
base: core18
version: '1.0.0'
summary: Support tools for rabbitmq-server
description: |
  This package contains tools that might be helpful in managing a
  RabbitMQ cluster.

  rebalance-queue-masters: given a RabbitMQ cluster with unevenly
    spread queue masters, this script will rebalance queue masters
    evenly, across all RabbitMQ nodes in the clustergreet usergreet
    usergreet user hithere greets the user, or the world.

grade: devel
confinement: strict

apps:
  rabbitmq-support:
    command: bin/rabbitmq-support

parts:
  support-tools:
    plugin: dump
    source: .
    source-commit: main
    stage-packages:
      - rabbitmq-server
    organize:
      rebalance-queue-masters: bin/
      rabbitmq-support: bin/
