name: rabbitmq-support-tools
base: core18
version: '20210713'
summary: Support tools for rabbitmq-server
description: |
  This package contains tools that might be helpful in managing a
  RabbitMQ cluster.

  rebalance-queue-masters: given a RabbitMQ cluster with unevenly spread queue
    masters, this script will rebalance queue masters evenly, across all RabbitMQ
    nodes in the clustergreet usergreet usergreet user hithere greets the user,
    or the world.

grade: devel
confinement: strict

apps:
  rabbitmq-support:
    command: bin/rabbitmq-support
  rebalance-queue-masters:
    command: bin/rebalance-queue-masters

parts:
  support-tools:
    plugin: dump
    source: https://github.com/nicolasbock/rabbitmq-support-tools.git
    source-commit: main
    organize:
      rebalance-queue-masters: bin/
      rabbitmq-support: bin/
