---

name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:

  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      - name: Store snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  build-deb:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Install package requirements
        run: |
          set -e -u -x

          sudo apt-get update
          sudo apt-get  --yes install --no-install-recommends \
            debmake \
            devscripts \
            fakeroot \
            libdistro-info-perl \
            software-properties-common \
            ubuntu-dev-tools \
            quilt
          pushd package
          sudo apt-get build-dep .
      - name: Generate binary package
        run: |
          set -e -u -x

          export DEBEMAIL=noreply@dev.null
          export DEBFULLNAME='CI Tester'

          git archive \
            --format tar.gz \
            --output rabbitmq-support-tools_99999999.orig.tar.gz \
            --prefix rabbitmq-support-tools-99999999/ \
            HEAD

          pushd package
          dch \
            --newversion 99999999 \
            --distribution focal \
            'CI test package'
          popd

          tar xf rabbitmq-support-tools_99999999.orig.tar.gz
          rsync -av package/debian rabbitmq-support-tools-99999999/
          pushd rabbitmq-support-tools-99999999
          dpkg-buildpackage -us -uc -ui
      - name: Store package artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: rabbitmq-support-tools_99999999_amd64.deb
