---

name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:

  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      - name: Store snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  build-deb:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Install package requirements
        run: |
          set -e -u -x

          sudo apt-get update
          sudo apt-get  --yes install --no-install-recommends \
            debmake \
            devscripts \
            fakeroot \
            libdistro-info-perl \
            software-properties-common \
            ubuntu-dev-tools \
            quilt
          pushd package
          sudo apt-get build-dep .
      - name: Generate Debian package
        run: |
          set -e -u -x

          export DEBEMAIL=noreply@dev.null
          export DEBFULLNAME='CI Tester'

          ./package/build-package.sh
      - name: Store package artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: rabbitmq-support-tools_*
